---
- name: copy the node-exporter to /usr/sbin/
  copy:
    src: node_exporter
    dest: /usr/sbin/node_exporter
    mode: 'u+x' 
- name: start the node-exporter
  shell: /usr/bin/nohup /usr/sbin/node_exporter &
- name: copy the process-monitor.py to the dest
  copy:
    src: process-monitor.py
    dest: /opt/
- name: prepare the virtual environment for process-monitor.py
  unarchive:
    src: process-monitor.tar.gz
    dest: /opt/
- name: start the process-monitor
  shell: source /opt/process-monitor/bin/activate && python /opt/process-monitor.py {{ harbor_url | default('harbor.' + os_subdomain) }}
# start node-exporter faled on some servers, debug it later
#- name: copy the service file 
#  copy:
#    src: node-exporter.service
#    dest: /usr/lib/systemd/system/node-exporter.service 
#
#- name: start the node service and enable start onboot
#  systemd: 
#    name: node-exporter
#    state: started
#    enabled: yes
#- name: open port 9100 for node_exporter
#  shell: iptables -I INPUT -p tcp --dport 9100 -j ACCEPT
