---

# Before deploy OpenShift
#- name: configure the basic of the host-repo set, install docker, set hostname, install node-exporter 
#  hosts: harbors 
#  roles:
#    - repoconfigure
#    - docker1.13.1 
#    - sethostname 
#    - expoter_install
#
#
#- name: install LDAP
#  hosts: ldapserver
#  roles:
#    - ldap 
#
#- name: install harbor and push the images requied during the deployment 
#  hosts: harbors
#  roles:
 #   - docker-compose
 #   - harbor
#    - dnsmasqinstall
#    - dnsconfigure
#    - baseImages4OS
#    - baseimage4caasportal
#    - images4portal
#- name: install NFS
#  hosts: nfsserver
#  roles:
#    - nfs
#- name: prepare for the openshift node
#  hosts: oscluster
#  roles:
    #- repoconfigure
    #- os_node_initial
    #- sethostname
    #- expoter_install
 #   - docker1.13.1
#

#- name: generate the inventory for deployer and deploy Openshift
#  hosts: deployers
#  roles:
#    - os_inventory
#    - os_deploy






# After OpenShift deployed

#Deploy Caasportal
#- name: deploy the caasportal
#  hosts: deployers
#  roles: 
#    - caasportal 
#Deploy Prometheus
- name: deploy the prometheus
  hosts: deployers
  roles:
    - prometheus
#Deploy EFK

