---

# Before deploy OpenShift
- name: configure the basic of the host-repo set, install docker, set hostname, install node-exporter 
  hosts: all 
  roles:
    - docker1.13.1 
    - sethostname 
    - expoter_install
    - repoconfigure


- name: install LDAP NFS harbor on storage server
  hosts: storage
  roles:
    - ldap 
    - docker-compose
    - harbor
    - dnsmasqinstall
    - dnsconfigure
    - baseImages4OS
    - baseimage4caasportal
    - images4portal

- name: prepare for the openshift node
  hosts: masters,nodes 
  roles:
    - os_node_initial


- name: generate the inventory for deployer and deploy Openshift
  hosts: "groups.masters[0]"
  roles:
    - os_inventory
    - os_deploy
    - caasportal
    - prometheus

