---
- name: open port on iptables| 8080 for muddle on nodes
  shell: iptables -nL|grep 8080 || iptables -I INPUT -p tcp --dport 8080 -j ACCEPT
- name: open port on iptables| 9100 for node_exporters on nodes
  shell: iptables -nL|grep 9100 || iptables -I INPUT -p tcp --dport 9100 -j ACCEPT
- name: open port on iptables| 9125 for process-monitor.py on nodes
  shell: iptables -nL|grep 9125 || iptables -I INPUT -p tcp --dport 9125 -j ACCEPT
