---

- name: set hosts for all the nodes in the OpenShift cluster
  template:
    src: hosts.j2
    dest: /etc/hosts

- name: create the storage for origin
  lvg:
    vg: "{{ os_vg }}"
    pvs: "{{ os_dev }}"

- name: create the lv for origin
  lvol:
    vg: "{{ os_vg }}"
    lv: "{{ os_lv }}"
    size: 100%FREE

- name: format the lv for origin
  filesystem:
    fstype: xfs
    dev: "/dev/{{ os_vg }}/{{ os_lv }}"

- name: mount the lv for os storage
  mount:
    path: /var/lib/origin/openshift.local.volumes
    src: "/dev/{{ os_vg }}/{{ os_lv }}"
    fstype: xfs
    state: mounted

- name: create the storage for data 
  lvg:
    vg: "{{ data_vg }}"
    pvs: "{{ data_dev }}"

- name: create the lv for data
  lvol:
    vg: "{{ data_vg }}"
    lv: "{{ data_lv }}"
    size: 100%FREE

- name: format the lv for data
  filesystem:
    fstype: xfs
    dev: "/dev/{{ data_vg }}/{{ data_lv }}"

- name: mount the lv for os storage
  mount:
    path: /caas_data/
    src: "/dev/{{ data_vg }}/{{ data_lv }}"
    fstype: xfs
    state: mounted

- name: install the required dependencies for OpenShift node
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - wget 
    - git
    - net-tools
    - bind-utils
    - iptables-services
    - bridge-utils
    - bash-completion
    - kexec-tools
    - sos 
    - psacct
    - nfs-utils
    - python-yaml
    - iptables
    - python-ipaddress
    - unzip
    - pyparted
    - python-devel
    - yum-utils
