---
#- name: unarchive the system requirements
#  unarchive:
#    src: /opt/installers/cent{{ os_version }}.tar 
#    dest: /opt/
#- name: unarchive the OpenShift repos
#  unarchive:
#    src: /opt/installers/os39.tar
#    dest: /opt/
- name: create yum repo | system
  shell:  nohup python -m SimpleHTTPServer 38888 &
  args:
    chdir: "/opt/cent{{ os_version }}"
#- name: create yum repo | Opeshift
#  shell: netstat -tlnp|grep 38888 || cd /opt/os39 && python -m SimpleHTTPServer 38889 &
- name: open port on iptables| 38888 
  shell: iptables -nL|grep 38888 || iptables -I INPUT -p tcp --dport 38888 -j ACCEPT
#- name: open port on iptables| 38889 
#  shell: iptables -nL|grep 38889 || iptables -I INPUT -p tcp --dport 38889 -j ACCEPT
