---
  - name: copy the nfs installer
    copy: 
      src: "/opt/installers/{{ item }}"
      dest: "/tmp/{{ item }}"
    with_items:
    - convert2nfs.zip
    - nfsenv.zip

  - name: unarchive the nfs installer
    unarchive: 
      src: "/tmp/{{ item }}"
      dest: /opt/
      remote_src: yes
    with_items:
    - convert2nfs.zip
    - nfsenv.zip

    
  - name: create the vg for nfs
    lvg:
      vg: "{{ nfs_vg }}"
      pvs: "{{ nfs_dev }}"

  - name: install the yum requirements
    yum: 
      name: "{{ item }}"
      state: present
    with_items:
    - nfs-utils
    - rpcbind
    - lvm2
    - gcc-c++
    - python-devel
  
  - name: start the nfs and rpcbind service 
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items:
    - rpcbind
    - nfs 

  
  - name: preinstall-add privilege
    shell:  chmod a+x bin/* 
    args:
      chdir: /opt/convert2nfs

  - name: create directory /nfs
    file:
      path: /nfs
      state: directory
      mode: 0755

  - name: install the interface
    shell: source /opt/nfsenv/bin/activate &&  python setup.py install
    args:
      chdir: /opt/convert2nfs

  - name: add the start  file
    template:
      src: startNfs.sh.j2
      dest: /usr/local/bin/startNfs.sh
      mode: 0751


  - name: add the  stop file
    template:
      src: stopNfs.sh.j2
      dest: /usr/local/bin/stopNfs.sh
      mode: 0751

  - name: add the service file
    copy:
      src: nfsinterface.service
      dest: /usr/lib/systemd/system/nfsinterface.service
      mode: 0644
  - name: reload the service
    shell: systemctl daemon-reload

  - name: start the convert2nfs
    service:
      name: nfsinterface.service
      state: started
      enabled: yes

