- name: copy sql - hcpaas-schema.sql
  template:
    src: hcpaas_schema.sql.j2
    dest: /tmp/hcpaas_schema.sql
- name: copy sql - hcappas_bmp_schema.sql
  copy:
    src: hcpaas_bmp_schema.sql 
    dest: /tmp/hcpaas_bmp_schema.sql
- name: MySQL | init mysql db
  command: "
    mysql -uroot -padminpwd -e
    \"
    SOURCE /tmp/hcpaas_schema.sql;
    SOURCE /tmp/hcpaas_bmp_schema.sql;
    \"
    "
- name: copy user clean script 
  copy: src=user_clear.sh dest=/data/mysql_data/ mode=0755
- name: clear useless user 
  shell: /data/mysql_data/user_clear.sh
