---
- name: install docker-compose 
  yum:
    name: docker-compose
    state: present
    update_cache: yes
    disable_gpg_check: yes

- name: check whether the docker-compose is ready
  shell: which docker-compose
