---
- name: copy the openshift ansible to deployer
  copy:
    src: /opt/installers/openshift-ansible39.tar
    dest: /tmp/

- name: unarchive the openshift ansible to deployer
  unarchive:
    src: /tmp/openshift-ansible39.tar
    dest: /opt/

- name: execute the play-book to deploy OpenShift according to the inventory generated
  command: ansible-playbook -i /opt/inventory /opt/openshift-ansible39/ansible-playbook/playbooks/playbooks/byo/config.yml
