---
- name: unarchive the openshift ansible to deployer
  unarchive:
    src: /opt/installers/openshift-ansible39.tar
    dest: /opt/
    remote_src: yes
#- name: execute the play-book to check the requirments of  OpenShift according to the inventory generated
#  shell: ansible-playbook -i /opt/inventory /opt/openshift-ansible39/playbooks/prerequisites.yml > /tmp/os_requirment.log

- name: execute the play-book to deploy OpenShift according to the inventory generated
  shell: ansible-playbook -i /opt/inventory /opt/openshift-ansible39/playbooks/deploy_cluster.yml   > /tmp/os_deploy.log
- name: grant cluster privileges 
  shell: oc adm policy add-cluster-role-to-user cluster-admin admin
