---
  - name: create bak to bakup the repo files
    file:
      path: /etc/yum.repos.d/bak
      state: directory
      mode: 0755
  
  - name: mv the original repo to bak
    shell: mv *.repo bak/
    args:
      chdir: /etc/yum.repos.d/
    ignore_errors: yes

  - name: set the repo for the os
    template: 
      src: sys.repo.j2
      dest: /etc/yum.repos.d/sys.repo
  - name: disable the firewalld
    systemd:
      name: firewalld
      state: stopped
      enabled: no
    when: nsible_distribution_version != "7.3.1611"
#  - name: set the repo for the os
#    template: 
#      src: os.repo.j2
#      dest: /etc/yum.repos.d/os.repo

 # - name: remove all the repo 
 #   shell:  ls |grep -v sys.repo
 #   register: repos
 #   args:
 #     chdir: /etc/yum.repos.d/
 # - name: remove the current repos execpt sys.repo
 #   shell: echo repos |xargs mv {} /etc/yum.repo.d/bak/
 #   when: repos.stdout !=""
 # - name: install the createrepo deltarpm 
 #   yum:
 #     name: /opt/cent{{ os_version }}/deltarpm-3.6-3.el7.x86_64.rpm 
 #     state: present

 # - name: install the createrepo python-deltarpm
 #   yum:
 #     name: /opt/cent{{ os_version }}/python-deltarpm-3.6-3.el7.x86_64.rpm
 #     state: present

 # - name: install the createrepo createrepo
 #   yum:
 #     name: /opt/cent{{ os_version }}/createrepo-0.9.9-28.el7.noarch.rpm
 #     state: present
