---
# this playbook is used to deploy all caas platform for POC
# NOTICE: images for appstore, platform and s2i not imported in this playbook
# Before deploy OpenShift
- name: create repo on master01 and create id_rsa file
  hosts: "{{ groups.masters[0] }}"
  roles:
    - createrepo
    - createauthorizedkeys

- name: configure the basic of the host-repo set, install docker, set hostname, install node-exporter 
  hosts: all 
  roles:
    - push_authorizedkeys
    - repoconfigure
    - docker1.13.1 
    - sethostname 
    - expoter_install



- name: install LDAP NFS harbor on storage server
  hosts: storage 
  roles:
    - nfs
    - dnsmasqinstall
    - dnsconfigure
    - ldap 
    - docker-compose
    - harbor
    - installmysql

- name: prepare for the openshift node
  hosts: masters,nodes 
  roles:
    - os_node_initial
    - dnsconfigure

    
- hosts: "{{ groups.masters[0] }}"
  tasks:
  - name: install java for deployer
    yum:
      name: java
      state: present
    

- name: generate the inventory for deployer and deploy Openshift
  hosts: "{{ groups.masters[0] }}"
  roles:
#    - baseImages4OS
#    - images4portal
    - os_inventory
    - os_deploy
    - caasportal
    - prometheus
    - addStorage2Logging
    - importIS



- name: deploy the tencale and processmonitor, set iptables for masters and nodes
  hosts: masters,nodes
  roles:
    - setiptables-os
    - process-monitor
    - tentacle


- name: save the iptables on all servers
  hosts: all
  tasks:
    - name: save the iptables
      shell: service iptables save